# This is a basic workflow to help you get started with Actions

name: Windows Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  buildWindows: 
      runs-on: windows-latest
      env: 
        WXWIN: D:\a\GorillaModManager\GorillaModManager\wxWidgets-3.1.3
      steps: 
      - uses: actions/checkout@v2
      - uses: egor-tensin/vs-shell@v2
      - uses: krdlab/setup-haxe@master
        with: 
         haxe-version: 4.2.4

      - name: Install Haxelibs
        run: |
           haxelib setup ~/haxelib
           haxelib install hxcpp
           haxelib git haxeui-core https://github.com/haxeui/haxeui-core.git
           haxelib git haxeui-hxwidgets https://github.com/haxeui/haxeui-hxwidgets.git
           haxelib install hxWidgets
           haxelib git haxeui-html5 https://github.com/haxeui/haxeui-html5.git
           haxelib install electron
           haxelib install hxnodejs
      - name: Install wxWidgets
        run: |
          C:\msys64\usr\bin\wget.exe https://github.com/wxWidgets/wxWidgets/releases/download/v3.1.3/wxWidgets-3.1.3.tar.bz2
          7z x wxWidgets-3.1.3.tar.bz2
          7z x wxWidgets-3.1.3.tar
          cd wxWidgets-3.1.3\build\msw
          nmake.exe -f makefile.vc BUILD=release TARGET_CPU=x64
          nmake.exe -f makefile.vc BUILD=release SHARED=1 TARGET_CPU=x64
          cd ..\..\..
      - name: Build CPP
        shell: powershell
        run: |
          npm i --always
          npx lessc assets/styles/bulbydark.less assets/styles/bulbydark.css
          haxe hxwidgets.hxml -D HXCPP_M64
          Copy-Item -Path "assets" -Destination "build/hxwidgets" -Recurse
          Remove-Item build/hxwidgets/include -Recurse -Force
          Remove-Item build/hxwidgets/obj -Recurse -Force
          Remove-Item build/hxwidgets/src -Recurse -Force
          Remove-Item build/hxwidgets/Build.xml -Force
          Remove-Item build/hxwidgets/Options.txt -Force
      - name: Publish Artifact
        uses: actions/upload-artifact@v2
        with: 
          name: windowsBuild
          path: 'build/hxwidgets/'
      - name: Build Electron
        shell: powershell
        run: |
          npx lessc assets/styles/bulbydark.less assets/styles/bulbydark.css
          haxe electron.hxml
        
          cd build/electron
          npm i --always
          npx electron-packager . GorillaModManager --out=out --asar
          Copy-Item -Path "assets" -Destination "build/electron/out/GorillaModManager-windows-x64" -Recurse
          cd ../..
      - name: Publish Electron App
        uses: actions/upload-artifact@v2
        with: 
          name: windowsElectron
          path: 'build/electron/out/GorillaModManager-windows-x64'



